version: '3.8'

services:
  postgres:
    container_name: postgres_container
    image: ankane/pgvector:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: learn_ai_python_dev
    volumes:
       - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
    pgdata: